routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
/*Route::get('/about', function (){
  $user_data = array(
      array(
          "name" => 'Ganesh',
          "phone" => '9848979669',
          "email" => 'bhattaganesh05@gmail.com',
          "address" => 'Kailali'
      ),
      array(
          "name" => 'Akon',
          "phone" => '98489476325',
          "email" => 'gp05@gmail.com',
          "address" => 'dhangadhi'
      )
  );
  return view('about')
      ->with("user_data" , $user_data)
      ->with("title","about Us Page");
})->name('about');*/
Route::get('/about',"UserController@about")->name("user.about");
Route::resource('/blog',"BlogController");
Route::get('/blog/test',"BlogController@test")->name('blog.test');

Route::get('/invoke','InvokableController');
Route::group(['prefix'=>'admin'],function (){
    Route::get('/about', function (){echo "this is about page";});
    Route::get('/join', function (){echo "this is join page";});
    Route::get('/index', function (){echo "this is index page";});
});


Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::group(['prefix'=>'/user','middleware'=>['auth','user']],function(){
Route::get('/', 'HomeController@user')->name('user');
});
Route::group(['prefix'=>'/admin','middleware'=>['auth','admin']],function(){
Route::get('/', 'HomeController@admin')->name('admin');
});

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Blog extends Model
{
    protected  $fillable = ['blog_title','blog_summary','slug','category_id','blog_description','blog_status','blog_image','added_by'];

    public function category_info(){
        return $this->hasOne('App\Models\Category','id','category_id');

    }
    public function  getRules(){
        return ([
            'blog_title' => ['required','string','max:100'],
            'category_id' => ['required','exists:categories,id'],
            'blog_summary' => ['required','string'],
            'blog_description' => "nullable|string",
            'blog_status' => "required|in:active,inactive",
//            'blog_image' => "sometimes|image|max:5000"
        ]);
    }

}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use function GuzzleHttp\Promise\all;
use App\Models\Category;
use App\Models\Blog;
use App\User;
use App\Mail\notify;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;
use Image;
use Mail;

$blog = new Blog();
class BlogController extends Controller
{
    protected $blog = null;
    public function __construct(Blog $blog){
        $this->blog = $blog;
        $this->middleware(['auth'])->except(['getAllBlogs']);
    }
    public function getAllBlogs(){
        return response()->json(
            [
                'data'=>$this->blog->get(),
                'status'=>true,
                'msg'=>'success'
            ]
        );
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
/*        $blog_data = array(
            array(
                "title" => 'Programmingpot',
                "summary" => 'This is a blog programming blog',
                "description" => 'This provides programming tutorials on front-end as well as backend.',
                "category" => 'Education',
                "status" => 'Published'
            ),
            array(
                "title" => 'Nepali Jokes',
                "summary" => 'This is a blog for entertainment',
                "description" => 'This provides funny jokes in nepali, hindi and english langauge.',
                "category" => 'Entertainment',
                "status" => 'Un-published'
            )
        );*/
//        $blog_data = $this->blog->paginate(5);
        $blog_data = $this->blog->latest()->get();
        return view('blog.index')->with("blog_data" , $blog_data)->with("title","Home Page");
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = new Category();
//      $all_cat = $category->get();
        $all_cat = $category->pluck('category_title','id');//(value,key)

//        dd($all_cat);
        return view("blog.blog_form_using_lc")->with("title","Blog Create Form")
            ->with("all_cat",$all_cat);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        /*
        dd($request);
        dd($request->only(['blog_summary','blog_description','blog_title']));
        dd($request->except(['blog_summary','blog_description','blog_title']));
          dd($request->input('blog_title'));
            dd($request->blog_title);
               $request->request->add(["is_featured"=>"true"]);
               $request->request->add(["blog_title" => "ksllaskfjasldjf"]);
                dd($request);
        */
        $rules = $request->validate($this->blog->getRules());
        $data = $request->all();
        $data['slug'] = \Str::slug($request->blog_title);
        if($request->hasFile('blog_image')){
            $extension = $request->file('blog_image')->getClientOriginalExtension();
            $folder_name = "blog_image".date('ymdhis').rand(0,999);
            $image = $request->file('blog_image')->storeAs($folder_name,"blob_image.".$extension,'public');
            $data['blog_image'] = $image;
            $path = storage_path('app/public/').$data['blog_image'];
            $thumb_success = Image::make($path)->resize(300,300,function ($constraint){
                return $constraint->aspectRatio();
            })->save($path);

        }
//        dd($data);
//        $inserted_data = $this->blog->create($data);
//        dd($inserted_data);
        $this->blog->fill($data);
    // dd($this->blog);
        $status = $this->blog->save();
        if($status){
            $user =  new User;
            $all_users = $user->get();
            foreach ($all_users as $all_user){
                Mail::to($all_user->email)->send(new notify($this->blog,$all_user->name));
            }
            return redirect()->route('blog.index')->with('success',"Blog inserted successfully");

        }else{
            return redirect()->route('blog.create')->with('error',"Soryy!, error while  inserting blog ");
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit_data = $this->blog->findOrFail($id);
        $category = new Category();
//        $all_cat = $category->get();
        $all_cat = $category->pluck('category_title','id');//(value,key)
//        dd($all_cat);
//        dd($edit_data);
//        return view('blog.blog_form',compact('$edit_data'));
        return view('blog.blog_form_using_lc')->with("edit_blog_data" , $edit_data)->with("title","Blog Edit form")
            ->with('all_cat',$all_cat);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = $request->validate($this->blog->getRules());
        $data = $request->all();
        $image_path = explode('/',$data['folder_name']);
            if(count($image_path)>1){
                $folder_name = $image_path[0];
            }else{
                $folder_name = "blog_image".date('ymdhis').rand(0,999);
            }
        $data['slug'] = \Str::slug($request->blog_title);
        if($request->hasFile('blog_image')){
            $extension = $request->file('blog_image')->getClientOriginalExtension();
            $image = $request->file('blog_image')->storeAs($folder_name,"blob_image.".$extension,'public');
            $data['blog_image'] = $image;
            $path = storage_path('app/public/').$data['blog_image'];
            $thumb_success = Image::make($path);
            $thumb_success->resize(300,300,function ($constraint){ return $constraint->aspectRatio();});
            $thumb_success->save($path);
        }
        $status = Blog::find($id)->update($data);;
        if($status){
            return redirect()->route('blog.index')->with('success',"Blog updated successfully");
        }else{
            return redirect()->route('blog.index')->with('error',"Sorry!, error while  updating blog ");
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $data = Blog::find($id);
        $file_check = $data['blog_image'];
        $file_check = explode('/',$file_check);
        $deleted = Blog::find($id)->delete();
        if(!$deleted){
            return redirect()->route('blog.index')->with('error',"Soryy!, error while  deleting blog");

        }else{
            if(count($file_check)>1){
                $path = storage_path('app/public/').$data->blog_image;
                if(File::exists($path)){
                    unlink($path);
                    rmdir(storage_path('app/public/'.$file_check[0]));
                }
            }
            return redirect()->route('blog.index')->with('success',"Blog deleted successfully");

        }

    }
    public function test($path){
        return Storage::url($path);
    }

}

resources/views/blog/blog_form.blade.php
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>{{$title ?? ''}}</title>
        <link rel="stylesheet" href="{{asset('css/app.css')}}">
        <link rel="stylesheet" href="{{asset('css/all.min.css')}}">
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-sm-12 col-lg-8  m-auto">
                    <div class="card mt-2">
                        @include('../flash_message')
                        <div class="card-header ">
                            <h5 class="font-weight-bold">{{$title ?? 'Blog Form'}}</h5>
                        </div>
                        <div class="card-body">
                            <form action="{{ isset($edit_blog_data)?route('blog.update',$edit_blog_data->id):route('blog.store') }}" method="post" enctype = "multipart/form-data" class = "form">
                                {{--                        @csrf--}}
                                <input type="hidden" name="_token" value="{{csrf_token()}}">
                                @if(isset($edit_blog_data))
                                @method('put')
                                @endif
                                <div class="form-group row">
                                    <div class="col-3 text-right">
                                        <label for="blog_title" class=" col-form-label ">Blog Title</label>
                                    </div>
                                    <div class="col-8">
                                        <input type="text" class="form-control " value="{{@$edit_blog_data->blog_title ?? old('blog_title')}}" required name="blog_title" id="blog_title" placeholder="Enter title for blog">
                                        @error('blog_title')
                                        <span class="alert-danger">{{ $message }}</span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-3 text-right">
                                        <label for="blog_summary" class=" col-form-label ">Summary</label>
                                    </div>
                                    <div class="col-8">
                                        <textarea style="resize: none;" required  class="form-control"  name="blog_summary" id="blog_summary" placeholder="Enter summary for blog">{{@$edit_blog_data->blog_summary ?? old('blog_summary')}}</textarea>
                                        @error('blog_summary')
                                        <span class="alert-danger">{{ $message }}</span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-3 text-right">
                                        <label for="blog_description" class=" col-form-label ">Description</label>
                                    </div>
                                    <div class="col-8">
                                        <textarea style="resize: none;" class="form-control " name="blog_description" id="blog_description" placeholder="Enter Description for blog">{{@$edit_blog_data->blog_description ?? old('blog_description')}}</textarea>
                                        @error('blog_description')
                                        <span class="alert-danger">{{ $message }}</span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-3 text-right">
                                        <label for="category_id" class=" col-form-label ">Blog Category</label>
                                    </div>
                                    <div class="col-8">
                                        <select  class="form-control " name="category_id" id="category_id" >
                                            <option value="" selected disabled>__Select-Category__</option>
                                            @if($all_cat->count())
                                            @foreach($all_cat as $cat)
                                            <option value="{{$cat->id}}" {{(@$edit_blog_data->category_id == $cat->id) ? 'selected': '' }}>{{$cat->category_title}}</option>
                                            @endforeach
                                            @endif;
                                        </select>
                                        @error('category_id')
                                        <span class="alert-danger">{{ $message }}</span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-3 text-right">
                                        <label for="blog_status" class=" col-form-label ">Blog Status</label>
                                    </div>
                                    <div class="col-8">
                                        <select class="form-control " name="blog_status" id="blog_status" >
                                            <option value="active" {{@$edit_blog_data->blog_status == 'active' ? 'selected' : '' }}>Published</option>
                                            <option value="inactive" {{@$edit_blog_data->blog_status == 'inactive' ? 'selected' : '' }}>Un-Published</option>
                                        </select>
                                        @error('blog_status')
                                        <span class="alert-danger">{{ $message }}</span>
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-3 text-right">
                                        <label for="blog_image" class=" col-form-label ">Image</label>
                                    </div>
                                    <div class="col-4">
                                        <input type="file" class="form-control-file " onchange="readURL(this,'thumb')" name="blog_image" id="blog_image" accept="image/*">
                                    </div>
                                    @error('blog_image')
                                    <span class="alert-danger">{{ $message }}</span>
                                    @enderror
                                    <div class="col-3">
                                        <img src="{{\Illuminate\Support\Facades\Storage::url(@$edit_blog_data->blog_image) ?? '' }}" alt="" class="img img-fluid" id="thumb" height="200px" width="200px">
                                    </div>
                                </div>
                                <input type="hidden" name="folder_name" value="{{@$edit_blog_data->blog_image}}">
                                <div class="form-group row">
                                    <div class="offset-3 col-8 ">
                                        <button type="submit" class="btn btn-success btn-block font-weight-bold">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <a href="{{route('blog.index')}}" style="text-decoration: none;"><i class="fa fa-lef-arrow"></i> Go Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src = "{{asset('js/app.js')}}"></script>
        <script>
        function readURL(input,image_id){
        if(input.files && input.files[0]){
        var reader  = new FileReader();
        reader.onload = function (e){
        $('#'+image_id)
        .attr('src',e.target.result);
        };
        reader.readAsDataURL(input.files[0]);
        }
        }
        </script>
    </body>
</html>

resources/views/blog/blog_form_using_lc.blade.php
@extends('../layouts.blog')
@section('container_class','container')
@section('main_content')
        <div class="col-md-8 col-sm-12 col-lg-8  m-auto">
            <div class="card mt-2">
                @include('../flash_message')
                <div class="card-header ">
                    <h5 class="font-weight-bold">{{$title ?? 'Blog Form'}}</h5>
                </div>
                <div class="card-body">
                    {{Form::open( ['url'=> (isset($edit_blog_data)?route('blog.update',$edit_blog_data->id):route('blog.store')),'files'=>true],['class'=>'form']) }}
                        @if(isset($edit_blog_data))
                            @method('put')
                        @endif
                        <div class="form-group row">
                            <div class="col-3 text-right">
                                {{Form::label('blog_title','Blog Title',['class'=>'col-form-label'])}}
                            </div>
                            <div class="col-8">
                                {{Form::text('blog_title',@$edit_blog_data->blog_title ?? old('blog_title'),['class' => 'form-control','id'=>'blog_title','required' => true,'placeholder' => 'Enter title for blog'] )}}
                                @error('blog_title')
                                <span class="alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-3 text-right">
                                {{Form::label('blog_summary','Summary',['class'=>'col-form-label'])}}
                            </div>
                            <div class="col-8">
                                {{Form::textarea('blog_summary',@$edit_blog_data->blog_summary ?? old('blog_summary'),['class' => 'form-control','id'=>'blog_summary','required' => true,'placeholder' => 'Enter summary for blog','rows' => 2,'style' => 'resize: none'] )}}
                                @error('blog_summary')
                                <span class="alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-3 text-right">
                                {{Form::label('blog_description','Description',['class'=>'col-form-label'])}}
                            </div>
                            <div class="col-8">
                                {{Form::textarea('blog_description',@$edit_blog_data->blog_description ?? old('blog_description'),['class' => 'form-control','id'=>'blog_description','required' => true,'placeholder' => 'Enter description for blog','rows' => 2,'style' => 'resize: none'] )}}@error('blog_description')
                                <span class="alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-3 text-right">
                                <label for="category_id" class=" col-form-label ">Blog Category</label>
                            </div>
                            <div class="col-8">
                                {{Form::select('category_id', $all_cat, @$edit_blog_data->category_id, ['placeholder' => '__Select-Category__','required' => true, 'id' => 'category_id' ,'class' => 'form-control'])}}
                                @error('category_id')
                                <span class="alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-3 text-right">
                                <label for="blog_status" class=" col-form-label ">Blog Status</label>
                            </div>
                            <div class="col-8">
                                {{Form::select('blog_status', ['active' => 'Published','inactive' => 'Un-published'], @$edit_blog_data->blog_status, ['required' => true, 'id' => 'blog_status' ,'class' => 'form-control'])}}
                                @error('blog_status')
                                <span class="alert-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-3 text-right">
                                <label for="blog_image" class=" col-form-label ">Image</label>
                            </div>
                            <div class="col-4">
                                <input type="file" class="form-control-file " onchange="readURL(this,'thumb')" name="blog_image" id="blog_image" accept="image/*">
{{--                                {{Form::file('blog_image',['accept' => 'image/*','id'=>'blog_image','class'=>'form-control-file','onchange'=>"readURL(this,'thumb')"])}}--}}
                            </div>
                            @error('blog_image')
                            <span class="alert-danger">{{ $message }}</span>
                            @enderror
                            <div class="col-3">
                                @if(@$edit_blog_data->blog_image)
                                    <img src="{{\Illuminate\Support\Facades\Storage::url(@$edit_blog_data->blog_image)}}" alt="" class="img-fluid" id="thumb">
                                @else
                                    <img src="" alt="" class="img img-fluid" id="thumb" >
                                @endif
                            </div>
                        </div>
                        {{Form::hidden('folder_name',@$edit_blog_data->blog_image)}}
                        <div class="form-group row">
                            <div class="offset-3 col-8 ">
                                {{Form::button('Submit',['type' => 'submit','class' => 'btn btn-success btn-block font-weight-bold'])}}
                            </div>
                        </div>
                   {{Form::close()}}
                </div>
                <div class="card-footer text-center">
                    <a href="{{route('blog.index')}}" style="text-decoration: none;"><i class="fa fa-lef-arrow"></i> Go Back</a>
                </div>
            </div>
        </div>
@endsection
@section('script_js')
    function readURL(input,image_id){
        if(input.files && input.files[0]){
            var reader  = new FileReader();
            reader.onload = function (e){
                $('#'+image_id)
                    .attr('src',e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
@endsection
</body>
</html>

resources/views/blog/index.blade.php
@php
use Illuminate\Support\Facades\Storage;
@endphp
@extends('../layouts.blog')
@section('header_content')
    <link rel="stylesheet" href="{{asset('plugins/datatables/datatables.min.css')}}">
@endsection
@section('container_class','container-fluid')
@section('main_content')
                <div class="col-4">
                    <h4 class="m-2 font-weight-bold">Blog List</h4>
                </div>
                <div class="  offset-4 col-4 text-right ">
                    <a href="{{route('blog.create')}}" class="btn btn-success m-2">Add Blog</a>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    @include('../flash_message')
                    <table class="table table-sm  table-hover table-bordered text-center table-striped">
                        <thead class="thead-dark">
                            <th>S.N.</th>
                            <th>Title</th>
                            <th>Summary</th>
                            <th>Description</th>
                            <th>Category</th>
                            <th>Status</th>
                            <th>Image</th>
                            <th>Action</th>
                        </thead>
                        <tbody>
                            @if($blog_data->count())
                            @foreach($blog_data  as  $value)
                            <tr>
                                <td>{{$value->id}}</td>
                                <td>{{$value->blog_title}}</td>
                                <td>{{$value->blog_summary}}</td>
                                <td>{{$value->blog_description}}</td>
                                <td>{{$value->category_info->category_title}}</td>
                                <td>{{$value->blog_status}}</td>
                                <td>
                                    @if(($value->blog_image))
                                    <img src="{{Storage::url($value->blog_image)}} " alt="" class="img-fluid img-thumbnail" width="100" height="100">
                                    @endif
                                </td>
                                <td>
                                    <form action="{{ route('blog.destroy',$value->id) }}" method="POST"  onsubmit= "return confirm('Are you sure, you want to this blog?')">
                                        <a href="{{route('blog.edit',$value->id)}}" class="" title="Edit this blog"><i class=" fa fa-pen"></i></a>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class=" btn btn-link" style="border: none;"><a href="javascript:;" title="Delete this blog"><i class="fa fa-trash"></i></a></button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                            @endif
                        </tbody>
                    </table>
                    {{--            <span>{{$blog_data->links()}}</span>--}}
                </div>
            </div>
@endsection
@section('footer_script_src')
<script src = "{{asset('js/app.js')}}"></script>
<script src = "{{asset('plugins/datatables/datatables.min.js')}}"></script>
@endsection
@section('script_js')
$('.table').DataTable();
@endsection
    </body>
</html>